services:
  - type: web
    name: tudory
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    disk:
      name: data
      mountPath: /var/www/html/data   # PHP'de kullandığın __DIR__/data ile aynı
      sizeGB: 1
