services:
  - type: web
    name: griffon-panel
    env: nixpacks
    region: frankfurt
    plan: starter
    autoDeploy: true

    startCommand: php -S 0.0.0.0:$PORT -t .

    healthCheckPath: /

    disk:
      name: users-db
      mountPath: /opt/render/project/src/data
      sizeGB: 1
